package cn.gov.dao;

import cn.gov.model.Article;
import cn.gov.model.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    int countByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    int deleteByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Delete({
        "delete from article",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Insert({
        "insert into article (id, bt, ",
        "lb, lrrq, xxly, ",
        "dbt, tjw, sfxs, ",
        "ydcs, gjc, zy, ",
        "slt, tzlj, nr)",
        "values (#{id,jdbcType=INTEGER}, #{bt,jdbcType=VARCHAR}, ",
        "#{lb,jdbcType=INTEGER}, #{lrrq,jdbcType=VARCHAR}, #{xxly,jdbcType=INTEGER}, ",
        "#{dbt,jdbcType=VARCHAR}, #{tjw,jdbcType=INTEGER}, #{sfxs,jdbcType=BIT}, ",
        "#{ydcs,jdbcType=INTEGER}, #{gjc,jdbcType=VARCHAR}, #{zy,jdbcType=VARCHAR}, ",
        "#{slt,jdbcType=VARCHAR}, #{tzlj,jdbcType=VARCHAR}, #{nr,jdbcType=LONGVARCHAR})"
    })
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    int insertSelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    List<Article> selectByExampleWithBLOBs(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    List<Article> selectByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, bt, lb, lrrq, xxly, dbt, tjw, sfxs, ydcs, gjc, zy, slt, tzlj, nr",
        "from article",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("ResultMapWithBLOBs")
    Article selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Update({
        "update article",
        "set bt = #{bt,jdbcType=VARCHAR},",
          "lb = #{lb,jdbcType=INTEGER},",
          "lrrq = #{lrrq,jdbcType=VARCHAR},",
          "xxly = #{xxly,jdbcType=INTEGER},",
          "dbt = #{dbt,jdbcType=VARCHAR},",
          "tjw = #{tjw,jdbcType=INTEGER},",
          "sfxs = #{sfxs,jdbcType=BIT},",
          "ydcs = #{ydcs,jdbcType=INTEGER},",
          "gjc = #{gjc,jdbcType=VARCHAR},",
          "zy = #{zy,jdbcType=VARCHAR},",
          "slt = #{slt,jdbcType=VARCHAR},",
          "tzlj = #{tzlj,jdbcType=VARCHAR},",
          "nr = #{nr,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    @Update({
        "update article",
        "set bt = #{bt,jdbcType=VARCHAR},",
          "lb = #{lb,jdbcType=INTEGER},",
          "lrrq = #{lrrq,jdbcType=VARCHAR},",
          "xxly = #{xxly,jdbcType=INTEGER},",
          "dbt = #{dbt,jdbcType=VARCHAR},",
          "tjw = #{tjw,jdbcType=INTEGER},",
          "sfxs = #{sfxs,jdbcType=BIT},",
          "ydcs = #{ydcs,jdbcType=INTEGER},",
          "gjc = #{gjc,jdbcType=VARCHAR},",
          "zy = #{zy,jdbcType=VARCHAR},",
          "slt = #{slt,jdbcType=VARCHAR},",
          "tzlj = #{tzlj,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Article record);
}