package cn.gov.dao;

import cn.gov.model.InspectReport;
import cn.gov.model.InspectReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface InspectReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    int countByExample(InspectReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    int deleteByExample(InspectReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    @Delete({
        "delete from inspect_report",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    @Insert({
        "insert into inspect_report (id, report_name, ",
        "report_contact, report_condition, ",
        "reported_name, reported_condition, ",
        "title, problem, ",
        "doc, inspect_id, ",
        "date, ip)",
        "values (#{id,jdbcType=INTEGER}, #{reportName,jdbcType=VARCHAR}, ",
        "#{reportContact,jdbcType=VARCHAR}, #{reportCondition,jdbcType=VARCHAR}, ",
        "#{reportedName,jdbcType=VARCHAR}, #{reportedCondition,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=VARCHAR}, #{problem,jdbcType=VARCHAR}, ",
        "#{doc,jdbcType=VARCHAR}, #{inspectId,jdbcType=INTEGER}, ",
        "#{date,jdbcType=TIMESTAMP}, #{ip,jdbcType=VARCHAR})"
    })
    int insert(InspectReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    int insertSelective(InspectReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    List<InspectReport> selectByExample(InspectReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, report_name, report_contact, report_condition, reported_name, reported_condition, ",
        "title, problem, doc, inspect_id, date, ip",
        "from inspect_report",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    InspectReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") InspectReport record, @Param("example") InspectReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") InspectReport record, @Param("example") InspectReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InspectReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspect_report
     *
     * @mbggenerated
     */
    @Update({
        "update inspect_report",
        "set report_name = #{reportName,jdbcType=VARCHAR},",
          "report_contact = #{reportContact,jdbcType=VARCHAR},",
          "report_condition = #{reportCondition,jdbcType=VARCHAR},",
          "reported_name = #{reportedName,jdbcType=VARCHAR},",
          "reported_condition = #{reportedCondition,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "problem = #{problem,jdbcType=VARCHAR},",
          "doc = #{doc,jdbcType=VARCHAR},",
          "inspect_id = #{inspectId,jdbcType=INTEGER},",
          "date = #{date,jdbcType=TIMESTAMP},",
          "ip = #{ip,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(InspectReport record);
}