package cn.gov.dao;

import cn.gov.model.LinkCategory;
import cn.gov.model.LinkCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface LinkCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    int countByExample(LinkCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    int deleteByExample(LinkCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    @Delete({
        "delete from link_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    @Insert({
        "insert into link_category (id, name, ",
        "sort)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{sort,jdbcType=INTEGER})"
    })
    int insert(LinkCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    int insertSelective(LinkCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    List<LinkCategory> selectByExample(LinkCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, sort",
        "from link_category",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    LinkCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LinkCategory record, @Param("example") LinkCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LinkCategory record, @Param("example") LinkCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LinkCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_category
     *
     * @mbggenerated
     */
    @Update({
        "update link_category",
        "set name = #{name,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LinkCategory record);
}