package cn.gov.dao;

import cn.gov.model.Links;
import cn.gov.model.LinksExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface LinksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    int countByExample(LinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    int deleteByExample(LinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    @Delete({
        "delete from links",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    @Insert({
        "insert into links (id, name, ",
        "url, sort, cat_id)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR}, #{sort,jdbcType=INTEGER}, #{catId,jdbcType=INTEGER})"
    })
    int insert(Links record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    int insertSelective(Links record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    List<Links> selectByExample(LinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, url, sort, cat_id",
        "from links",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Links selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Links record, @Param("example") LinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Links record, @Param("example") LinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Links record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table links
     *
     * @mbggenerated
     */
    @Update({
        "update links",
        "set name = #{name,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "sort = #{sort,jdbcType=INTEGER},",
          "cat_id = #{catId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Links record);
}