package cn.gov.dao;

import cn.gov.model.MessageReply;
import cn.gov.model.MessageReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MessageReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    int countByExample(MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    int deleteByExample(MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    @Delete({
        "delete from message_reply",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    @Insert({
        "insert into message_reply (id, date, ",
        "message_id, reply)",
        "values (#{id,jdbcType=INTEGER}, #{date,jdbcType=TIMESTAMP}, ",
        "#{messageId,jdbcType=INTEGER}, #{reply,jdbcType=LONGVARCHAR})"
    })
    int insert(MessageReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    int insertSelective(MessageReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    List<MessageReply> selectByExampleWithBLOBs(MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    List<MessageReply> selectByExample(MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, date, message_id, reply",
        "from message_reply",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("ResultMapWithBLOBs")
    MessageReply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MessageReply record, @Param("example") MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") MessageReply record, @Param("example") MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MessageReply record, @Param("example") MessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MessageReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    @Update({
        "update message_reply",
        "set date = #{date,jdbcType=TIMESTAMP},",
          "message_id = #{messageId,jdbcType=INTEGER},",
          "reply = #{reply,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(MessageReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_reply
     *
     * @mbggenerated
     */
    @Update({
        "update message_reply",
        "set date = #{date,jdbcType=TIMESTAMP},",
          "message_id = #{messageId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(MessageReply record);
}