package cn.gov.dao;

import cn.gov.model.Report;
import cn.gov.model.ReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int countByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int deleteByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    @Delete({
        "delete from report",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    @Insert({
        "insert into report (id, report_name, ",
        "report_contact, report_condition, ",
        "reported_name, reported_condition, ",
        "title, problem, ",
        "doc, date, ip)",
        "values (#{id,jdbcType=INTEGER}, #{reportName,jdbcType=VARCHAR}, ",
        "#{reportContact,jdbcType=VARCHAR}, #{reportCondition,jdbcType=VARCHAR}, ",
        "#{reportedName,jdbcType=VARCHAR}, #{reportedCondition,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=VARCHAR}, #{problem,jdbcType=VARCHAR}, ",
        "#{doc,jdbcType=VARCHAR}, #{date,jdbcType=TIMESTAMP}, #{ip,jdbcType=VARCHAR})"
    })
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    List<Report> selectByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, report_name, report_contact, report_condition, reported_name, reported_condition, ",
        "title, problem, doc, date, ip",
        "from report",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Report selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report
     *
     * @mbggenerated
     */
    @Update({
        "update report",
        "set report_name = #{reportName,jdbcType=VARCHAR},",
          "report_contact = #{reportContact,jdbcType=VARCHAR},",
          "report_condition = #{reportCondition,jdbcType=VARCHAR},",
          "reported_name = #{reportedName,jdbcType=VARCHAR},",
          "reported_condition = #{reportedCondition,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "problem = #{problem,jdbcType=VARCHAR},",
          "doc = #{doc,jdbcType=VARCHAR},",
          "date = #{date,jdbcType=TIMESTAMP},",
          "ip = #{ip,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Report record);
}