package cn.gov.dao;

import cn.gov.model.ReportAdmin;
import cn.gov.model.ReportAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReportAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    int countByExample(ReportAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    int deleteByExample(ReportAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    @Delete({
        "delete from report_admin",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    @Insert({
        "insert into report_admin (username, password)",
        "values (#{username,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR})"
    })
    int insert(ReportAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    int insertSelective(ReportAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    List<ReportAdmin> selectByExample(ReportAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "username, password",
        "from report_admin",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    ReportAdmin selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReportAdmin record, @Param("example") ReportAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReportAdmin record, @Param("example") ReportAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_admin
     *
     * @mbggenerated
     */
    @Update({
        "update report_admin",
        "set password = #{password,jdbcType=VARCHAR}",
        "where username = #{username,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReportAdmin record);
}