package cn.gov.dao;

import cn.gov.model.ReportMsg;
import cn.gov.model.ReportMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ReportMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    int countByExample(ReportMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    int deleteByExample(ReportMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    @Delete({
        "delete from report_msg",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    @Insert({
        "insert into report_msg (id, report_name, ",
        "report_id, report_contact, ",
        "report_status, report_address, ",
        "report_level, reported_name, ",
        "reported_org, reported_post, ",
        "reported_level, title, ",
        "problem_type, problem_type_detail, ",
        "answer, answered, signed, ",
        "org, date, ip, ",
        "problem)",
        "values (#{id,jdbcType=VARCHAR}, #{reportName,jdbcType=VARCHAR}, ",
        "#{reportId,jdbcType=VARCHAR}, #{reportContact,jdbcType=VARCHAR}, ",
        "#{reportStatus,jdbcType=VARCHAR}, #{reportAddress,jdbcType=VARCHAR}, ",
        "#{reportLevel,jdbcType=VARCHAR}, #{reportedName,jdbcType=VARCHAR}, ",
        "#{reportedOrg,jdbcType=VARCHAR}, #{reportedPost,jdbcType=VARCHAR}, ",
        "#{reportedLevel,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
        "#{problemType,jdbcType=VARCHAR}, #{problemTypeDetail,jdbcType=VARCHAR}, ",
        "#{answer,jdbcType=VARCHAR}, #{answered,jdbcType=BIT}, #{signed,jdbcType=BIT}, ",
        "#{org,jdbcType=VARCHAR}, #{date,jdbcType=TIMESTAMP}, #{ip,jdbcType=VARCHAR}, ",
        "#{problem,jdbcType=LONGVARCHAR})"
    })
    int insert(ReportMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    int insertSelective(ReportMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    List<ReportMsg> selectByExampleWithBLOBs(ReportMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    List<ReportMsg> selectByExample(ReportMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, report_name, report_id, report_contact, report_status, report_address, report_level, ",
        "reported_name, reported_org, reported_post, reported_level, title, problem_type, ",
        "problem_type_detail, answer, answered, signed, org, date, ip, problem",
        "from report_msg",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    ReportMsg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReportMsg record, @Param("example") ReportMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ReportMsg record, @Param("example") ReportMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReportMsg record, @Param("example") ReportMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReportMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    @Update({
        "update report_msg",
        "set report_name = #{reportName,jdbcType=VARCHAR},",
          "report_id = #{reportId,jdbcType=VARCHAR},",
          "report_contact = #{reportContact,jdbcType=VARCHAR},",
          "report_status = #{reportStatus,jdbcType=VARCHAR},",
          "report_address = #{reportAddress,jdbcType=VARCHAR},",
          "report_level = #{reportLevel,jdbcType=VARCHAR},",
          "reported_name = #{reportedName,jdbcType=VARCHAR},",
          "reported_org = #{reportedOrg,jdbcType=VARCHAR},",
          "reported_post = #{reportedPost,jdbcType=VARCHAR},",
          "reported_level = #{reportedLevel,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "problem_type = #{problemType,jdbcType=VARCHAR},",
          "problem_type_detail = #{problemTypeDetail,jdbcType=VARCHAR},",
          "answer = #{answer,jdbcType=VARCHAR},",
          "answered = #{answered,jdbcType=BIT},",
          "signed = #{signed,jdbcType=BIT},",
          "org = #{org,jdbcType=VARCHAR},",
          "date = #{date,jdbcType=TIMESTAMP},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "problem = #{problem,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(ReportMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    @Update({
        "update report_msg",
        "set report_name = #{reportName,jdbcType=VARCHAR},",
          "report_id = #{reportId,jdbcType=VARCHAR},",
          "report_contact = #{reportContact,jdbcType=VARCHAR},",
          "report_status = #{reportStatus,jdbcType=VARCHAR},",
          "report_address = #{reportAddress,jdbcType=VARCHAR},",
          "report_level = #{reportLevel,jdbcType=VARCHAR},",
          "reported_name = #{reportedName,jdbcType=VARCHAR},",
          "reported_org = #{reportedOrg,jdbcType=VARCHAR},",
          "reported_post = #{reportedPost,jdbcType=VARCHAR},",
          "reported_level = #{reportedLevel,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "problem_type = #{problemType,jdbcType=VARCHAR},",
          "problem_type_detail = #{problemTypeDetail,jdbcType=VARCHAR},",
          "answer = #{answer,jdbcType=VARCHAR},",
          "answered = #{answered,jdbcType=BIT},",
          "signed = #{signed,jdbcType=BIT},",
          "org = #{org,jdbcType=VARCHAR},",
          "date = #{date,jdbcType=TIMESTAMP},",
          "ip = #{ip,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(ReportMsg record);
}