package cn.gov.dao;

import cn.gov.model.Source;
import cn.gov.model.SourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface SourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int countByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int deleteByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    @Delete({
        "delete from source",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    @Insert({
        "insert into source (id, mc, ",
        "px)",
        "values (#{id,jdbcType=INTEGER}, #{mc,jdbcType=VARCHAR}, ",
        "#{px,jdbcType=INTEGER})"
    })
    int insert(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int insertSelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    List<Source> selectByExample(SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, mc, px",
        "from source",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Source selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Source record, @Param("example") SourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    @Update({
        "update source",
        "set mc = #{mc,jdbcType=VARCHAR},",
          "px = #{px,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Source record);
}