package cn.gov.dao;

import cn.gov.model.TopicComment;
import cn.gov.model.TopicCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface TopicCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    int countByExample(TopicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    int deleteByExample(TopicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    @Delete({
        "delete from topic_comment",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    @Insert({
        "insert into topic_comment (id, net_name, ",
        "ip, comment, date, ",
        "display, topic_id, telephone)",
        "values (#{id,jdbcType=INTEGER}, #{netName,jdbcType=VARCHAR}, ",
        "#{ip,jdbcType=VARCHAR}, #{comment,jdbcType=VARCHAR}, #{date,jdbcType=TIMESTAMP}, ",
        "#{display,jdbcType=BIT}, #{topicId,jdbcType=INTEGER}, #{telephone,jdbcType=VARCHAR})"
    })
    int insert(TopicComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    int insertSelective(TopicComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    List<TopicComment> selectByExample(TopicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, net_name, ip, comment, date, display, topic_id, telephone",
        "from topic_comment",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    TopicComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TopicComment record, @Param("example") TopicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TopicComment record, @Param("example") TopicCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TopicComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topic_comment
     *
     * @mbggenerated
     */
    @Update({
        "update topic_comment",
        "set net_name = #{netName,jdbcType=VARCHAR},",
          "ip = #{ip,jdbcType=VARCHAR},",
          "comment = #{comment,jdbcType=VARCHAR},",
          "date = #{date,jdbcType=TIMESTAMP},",
          "display = #{display,jdbcType=BIT},",
          "topic_id = #{topicId,jdbcType=INTEGER},",
          "telephone = #{telephone,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TopicComment record);
}