package cn.gov.model;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.bt
     *
     * @mbggenerated
     */
    private String bt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.lb
     *
     * @mbggenerated
     */
    private Integer lb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.lrrq
     *
     * @mbggenerated
     */
    private String lrrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.xxly
     *
     * @mbggenerated
     */
    private Integer xxly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.dbt
     *
     * @mbggenerated
     */
    private String dbt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tjw
     *
     * @mbggenerated
     */
    private Integer tjw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.sfxs
     *
     * @mbggenerated
     */
    private Boolean sfxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ydcs
     *
     * @mbggenerated
     */
    private Integer ydcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.gjc
     *
     * @mbggenerated
     */
    private String gjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.zy
     *
     * @mbggenerated
     */
    private String zy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.slt
     *
     * @mbggenerated
     */
    private String slt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.tzlj
     *
     * @mbggenerated
     */
    private String tzlj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.nr
     *
     * @mbggenerated
     */
    private String nr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.bt
     *
     * @return the value of article.bt
     *
     * @mbggenerated
     */
    public String getBt() {
        return bt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.bt
     *
     * @param bt the value for article.bt
     *
     * @mbggenerated
     */
    public void setBt(String bt) {
        this.bt = bt == null ? null : bt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.lb
     *
     * @return the value of article.lb
     *
     * @mbggenerated
     */
    public Integer getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.lb
     *
     * @param lb the value for article.lb
     *
     * @mbggenerated
     */
    public void setLb(Integer lb) {
        this.lb = lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.lrrq
     *
     * @return the value of article.lrrq
     *
     * @mbggenerated
     */
    public String getLrrq() {
        return lrrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.lrrq
     *
     * @param lrrq the value for article.lrrq
     *
     * @mbggenerated
     */
    public void setLrrq(String lrrq) {
        this.lrrq = lrrq == null ? null : lrrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.xxly
     *
     * @return the value of article.xxly
     *
     * @mbggenerated
     */
    public Integer getXxly() {
        return xxly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.xxly
     *
     * @param xxly the value for article.xxly
     *
     * @mbggenerated
     */
    public void setXxly(Integer xxly) {
        this.xxly = xxly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.dbt
     *
     * @return the value of article.dbt
     *
     * @mbggenerated
     */
    public String getDbt() {
        return dbt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.dbt
     *
     * @param dbt the value for article.dbt
     *
     * @mbggenerated
     */
    public void setDbt(String dbt) {
        this.dbt = dbt == null ? null : dbt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tjw
     *
     * @return the value of article.tjw
     *
     * @mbggenerated
     */
    public Integer getTjw() {
        return tjw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tjw
     *
     * @param tjw the value for article.tjw
     *
     * @mbggenerated
     */
    public void setTjw(Integer tjw) {
        this.tjw = tjw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.sfxs
     *
     * @return the value of article.sfxs
     *
     * @mbggenerated
     */
    public Boolean getSfxs() {
        return sfxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.sfxs
     *
     * @param sfxs the value for article.sfxs
     *
     * @mbggenerated
     */
    public void setSfxs(Boolean sfxs) {
        this.sfxs = sfxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ydcs
     *
     * @return the value of article.ydcs
     *
     * @mbggenerated
     */
    public Integer getYdcs() {
        return ydcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ydcs
     *
     * @param ydcs the value for article.ydcs
     *
     * @mbggenerated
     */
    public void setYdcs(Integer ydcs) {
        this.ydcs = ydcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.gjc
     *
     * @return the value of article.gjc
     *
     * @mbggenerated
     */
    public String getGjc() {
        return gjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.gjc
     *
     * @param gjc the value for article.gjc
     *
     * @mbggenerated
     */
    public void setGjc(String gjc) {
        this.gjc = gjc == null ? null : gjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.zy
     *
     * @return the value of article.zy
     *
     * @mbggenerated
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.zy
     *
     * @param zy the value for article.zy
     *
     * @mbggenerated
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.slt
     *
     * @return the value of article.slt
     *
     * @mbggenerated
     */
    public String getSlt() {
        return slt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.slt
     *
     * @param slt the value for article.slt
     *
     * @mbggenerated
     */
    public void setSlt(String slt) {
        this.slt = slt == null ? null : slt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.tzlj
     *
     * @return the value of article.tzlj
     *
     * @mbggenerated
     */
    public String getTzlj() {
        return tzlj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.tzlj
     *
     * @param tzlj the value for article.tzlj
     *
     * @mbggenerated
     */
    public void setTzlj(String tzlj) {
        this.tzlj = tzlj == null ? null : tzlj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.nr
     *
     * @return the value of article.nr
     *
     * @mbggenerated
     */
    public String getNr() {
        return nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.nr
     *
     * @param nr the value for article.nr
     *
     * @mbggenerated
     */
    public void setNr(String nr) {
        this.nr = nr == null ? null : nr.trim();
    }
}