package cn.gov.model;

import java.util.ArrayList;
import java.util.List;

public class ArticleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public ArticleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBtIsNull() {
            addCriterion("bt is null");
            return (Criteria) this;
        }

        public Criteria andBtIsNotNull() {
            addCriterion("bt is not null");
            return (Criteria) this;
        }

        public Criteria andBtEqualTo(String value) {
            addCriterion("bt =", value, "bt");
            return (Criteria) this;
        }

        public Criteria andBtNotEqualTo(String value) {
            addCriterion("bt <>", value, "bt");
            return (Criteria) this;
        }

        public Criteria andBtGreaterThan(String value) {
            addCriterion("bt >", value, "bt");
            return (Criteria) this;
        }

        public Criteria andBtGreaterThanOrEqualTo(String value) {
            addCriterion("bt >=", value, "bt");
            return (Criteria) this;
        }

        public Criteria andBtLessThan(String value) {
            addCriterion("bt <", value, "bt");
            return (Criteria) this;
        }

        public Criteria andBtLessThanOrEqualTo(String value) {
            addCriterion("bt <=", value, "bt");
            return (Criteria) this;
        }

        public Criteria andBtLike(String value) {
            addCriterion("bt like", value, "bt");
            return (Criteria) this;
        }

        public Criteria andBtNotLike(String value) {
            addCriterion("bt not like", value, "bt");
            return (Criteria) this;
        }

        public Criteria andBtIn(List<String> values) {
            addCriterion("bt in", values, "bt");
            return (Criteria) this;
        }

        public Criteria andBtNotIn(List<String> values) {
            addCriterion("bt not in", values, "bt");
            return (Criteria) this;
        }

        public Criteria andBtBetween(String value1, String value2) {
            addCriterion("bt between", value1, value2, "bt");
            return (Criteria) this;
        }

        public Criteria andBtNotBetween(String value1, String value2) {
            addCriterion("bt not between", value1, value2, "bt");
            return (Criteria) this;
        }

        public Criteria andLbIsNull() {
            addCriterion("lb is null");
            return (Criteria) this;
        }

        public Criteria andLbIsNotNull() {
            addCriterion("lb is not null");
            return (Criteria) this;
        }

        public Criteria andLbEqualTo(Integer value) {
            addCriterion("lb =", value, "lb");
            return (Criteria) this;
        }

        public Criteria andLbNotEqualTo(Integer value) {
            addCriterion("lb <>", value, "lb");
            return (Criteria) this;
        }

        public Criteria andLbGreaterThan(Integer value) {
            addCriterion("lb >", value, "lb");
            return (Criteria) this;
        }

        public Criteria andLbGreaterThanOrEqualTo(Integer value) {
            addCriterion("lb >=", value, "lb");
            return (Criteria) this;
        }

        public Criteria andLbLessThan(Integer value) {
            addCriterion("lb <", value, "lb");
            return (Criteria) this;
        }

        public Criteria andLbLessThanOrEqualTo(Integer value) {
            addCriterion("lb <=", value, "lb");
            return (Criteria) this;
        }

        public Criteria andLbIn(List<Integer> values) {
            addCriterion("lb in", values, "lb");
            return (Criteria) this;
        }

        public Criteria andLbNotIn(List<Integer> values) {
            addCriterion("lb not in", values, "lb");
            return (Criteria) this;
        }

        public Criteria andLbBetween(Integer value1, Integer value2) {
            addCriterion("lb between", value1, value2, "lb");
            return (Criteria) this;
        }

        public Criteria andLbNotBetween(Integer value1, Integer value2) {
            addCriterion("lb not between", value1, value2, "lb");
            return (Criteria) this;
        }

        public Criteria andLrrqIsNull() {
            addCriterion("lrrq is null");
            return (Criteria) this;
        }

        public Criteria andLrrqIsNotNull() {
            addCriterion("lrrq is not null");
            return (Criteria) this;
        }

        public Criteria andLrrqEqualTo(String value) {
            addCriterion("lrrq =", value, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqNotEqualTo(String value) {
            addCriterion("lrrq <>", value, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqGreaterThan(String value) {
            addCriterion("lrrq >", value, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqGreaterThanOrEqualTo(String value) {
            addCriterion("lrrq >=", value, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqLessThan(String value) {
            addCriterion("lrrq <", value, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqLessThanOrEqualTo(String value) {
            addCriterion("lrrq <=", value, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqLike(String value) {
            addCriterion("lrrq like", value, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqNotLike(String value) {
            addCriterion("lrrq not like", value, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqIn(List<String> values) {
            addCriterion("lrrq in", values, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqNotIn(List<String> values) {
            addCriterion("lrrq not in", values, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqBetween(String value1, String value2) {
            addCriterion("lrrq between", value1, value2, "lrrq");
            return (Criteria) this;
        }

        public Criteria andLrrqNotBetween(String value1, String value2) {
            addCriterion("lrrq not between", value1, value2, "lrrq");
            return (Criteria) this;
        }

        public Criteria andXxlyIsNull() {
            addCriterion("xxly is null");
            return (Criteria) this;
        }

        public Criteria andXxlyIsNotNull() {
            addCriterion("xxly is not null");
            return (Criteria) this;
        }

        public Criteria andXxlyEqualTo(Integer value) {
            addCriterion("xxly =", value, "xxly");
            return (Criteria) this;
        }

        public Criteria andXxlyNotEqualTo(Integer value) {
            addCriterion("xxly <>", value, "xxly");
            return (Criteria) this;
        }

        public Criteria andXxlyGreaterThan(Integer value) {
            addCriterion("xxly >", value, "xxly");
            return (Criteria) this;
        }

        public Criteria andXxlyGreaterThanOrEqualTo(Integer value) {
            addCriterion("xxly >=", value, "xxly");
            return (Criteria) this;
        }

        public Criteria andXxlyLessThan(Integer value) {
            addCriterion("xxly <", value, "xxly");
            return (Criteria) this;
        }

        public Criteria andXxlyLessThanOrEqualTo(Integer value) {
            addCriterion("xxly <=", value, "xxly");
            return (Criteria) this;
        }

        public Criteria andXxlyIn(List<Integer> values) {
            addCriterion("xxly in", values, "xxly");
            return (Criteria) this;
        }

        public Criteria andXxlyNotIn(List<Integer> values) {
            addCriterion("xxly not in", values, "xxly");
            return (Criteria) this;
        }

        public Criteria andXxlyBetween(Integer value1, Integer value2) {
            addCriterion("xxly between", value1, value2, "xxly");
            return (Criteria) this;
        }

        public Criteria andXxlyNotBetween(Integer value1, Integer value2) {
            addCriterion("xxly not between", value1, value2, "xxly");
            return (Criteria) this;
        }

        public Criteria andDbtIsNull() {
            addCriterion("dbt is null");
            return (Criteria) this;
        }

        public Criteria andDbtIsNotNull() {
            addCriterion("dbt is not null");
            return (Criteria) this;
        }

        public Criteria andDbtEqualTo(String value) {
            addCriterion("dbt =", value, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtNotEqualTo(String value) {
            addCriterion("dbt <>", value, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtGreaterThan(String value) {
            addCriterion("dbt >", value, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtGreaterThanOrEqualTo(String value) {
            addCriterion("dbt >=", value, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtLessThan(String value) {
            addCriterion("dbt <", value, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtLessThanOrEqualTo(String value) {
            addCriterion("dbt <=", value, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtLike(String value) {
            addCriterion("dbt like", value, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtNotLike(String value) {
            addCriterion("dbt not like", value, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtIn(List<String> values) {
            addCriterion("dbt in", values, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtNotIn(List<String> values) {
            addCriterion("dbt not in", values, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtBetween(String value1, String value2) {
            addCriterion("dbt between", value1, value2, "dbt");
            return (Criteria) this;
        }

        public Criteria andDbtNotBetween(String value1, String value2) {
            addCriterion("dbt not between", value1, value2, "dbt");
            return (Criteria) this;
        }

        public Criteria andTjwIsNull() {
            addCriterion("tjw is null");
            return (Criteria) this;
        }

        public Criteria andTjwIsNotNull() {
            addCriterion("tjw is not null");
            return (Criteria) this;
        }

        public Criteria andTjwEqualTo(Integer value) {
            addCriterion("tjw =", value, "tjw");
            return (Criteria) this;
        }

        public Criteria andTjwNotEqualTo(Integer value) {
            addCriterion("tjw <>", value, "tjw");
            return (Criteria) this;
        }

        public Criteria andTjwGreaterThan(Integer value) {
            addCriterion("tjw >", value, "tjw");
            return (Criteria) this;
        }

        public Criteria andTjwGreaterThanOrEqualTo(Integer value) {
            addCriterion("tjw >=", value, "tjw");
            return (Criteria) this;
        }

        public Criteria andTjwLessThan(Integer value) {
            addCriterion("tjw <", value, "tjw");
            return (Criteria) this;
        }

        public Criteria andTjwLessThanOrEqualTo(Integer value) {
            addCriterion("tjw <=", value, "tjw");
            return (Criteria) this;
        }

        public Criteria andTjwIn(List<Integer> values) {
            addCriterion("tjw in", values, "tjw");
            return (Criteria) this;
        }

        public Criteria andTjwNotIn(List<Integer> values) {
            addCriterion("tjw not in", values, "tjw");
            return (Criteria) this;
        }

        public Criteria andTjwBetween(Integer value1, Integer value2) {
            addCriterion("tjw between", value1, value2, "tjw");
            return (Criteria) this;
        }

        public Criteria andTjwNotBetween(Integer value1, Integer value2) {
            addCriterion("tjw not between", value1, value2, "tjw");
            return (Criteria) this;
        }

        public Criteria andSfxsIsNull() {
            addCriterion("sfxs is null");
            return (Criteria) this;
        }

        public Criteria andSfxsIsNotNull() {
            addCriterion("sfxs is not null");
            return (Criteria) this;
        }

        public Criteria andSfxsEqualTo(Boolean value) {
            addCriterion("sfxs =", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsNotEqualTo(Boolean value) {
            addCriterion("sfxs <>", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsGreaterThan(Boolean value) {
            addCriterion("sfxs >", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsGreaterThanOrEqualTo(Boolean value) {
            addCriterion("sfxs >=", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsLessThan(Boolean value) {
            addCriterion("sfxs <", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsLessThanOrEqualTo(Boolean value) {
            addCriterion("sfxs <=", value, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsIn(List<Boolean> values) {
            addCriterion("sfxs in", values, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsNotIn(List<Boolean> values) {
            addCriterion("sfxs not in", values, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsBetween(Boolean value1, Boolean value2) {
            addCriterion("sfxs between", value1, value2, "sfxs");
            return (Criteria) this;
        }

        public Criteria andSfxsNotBetween(Boolean value1, Boolean value2) {
            addCriterion("sfxs not between", value1, value2, "sfxs");
            return (Criteria) this;
        }

        public Criteria andYdcsIsNull() {
            addCriterion("ydcs is null");
            return (Criteria) this;
        }

        public Criteria andYdcsIsNotNull() {
            addCriterion("ydcs is not null");
            return (Criteria) this;
        }

        public Criteria andYdcsEqualTo(Integer value) {
            addCriterion("ydcs =", value, "ydcs");
            return (Criteria) this;
        }

        public Criteria andYdcsNotEqualTo(Integer value) {
            addCriterion("ydcs <>", value, "ydcs");
            return (Criteria) this;
        }

        public Criteria andYdcsGreaterThan(Integer value) {
            addCriterion("ydcs >", value, "ydcs");
            return (Criteria) this;
        }

        public Criteria andYdcsGreaterThanOrEqualTo(Integer value) {
            addCriterion("ydcs >=", value, "ydcs");
            return (Criteria) this;
        }

        public Criteria andYdcsLessThan(Integer value) {
            addCriterion("ydcs <", value, "ydcs");
            return (Criteria) this;
        }

        public Criteria andYdcsLessThanOrEqualTo(Integer value) {
            addCriterion("ydcs <=", value, "ydcs");
            return (Criteria) this;
        }

        public Criteria andYdcsIn(List<Integer> values) {
            addCriterion("ydcs in", values, "ydcs");
            return (Criteria) this;
        }

        public Criteria andYdcsNotIn(List<Integer> values) {
            addCriterion("ydcs not in", values, "ydcs");
            return (Criteria) this;
        }

        public Criteria andYdcsBetween(Integer value1, Integer value2) {
            addCriterion("ydcs between", value1, value2, "ydcs");
            return (Criteria) this;
        }

        public Criteria andYdcsNotBetween(Integer value1, Integer value2) {
            addCriterion("ydcs not between", value1, value2, "ydcs");
            return (Criteria) this;
        }

        public Criteria andGjcIsNull() {
            addCriterion("gjc is null");
            return (Criteria) this;
        }

        public Criteria andGjcIsNotNull() {
            addCriterion("gjc is not null");
            return (Criteria) this;
        }

        public Criteria andGjcEqualTo(String value) {
            addCriterion("gjc =", value, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcNotEqualTo(String value) {
            addCriterion("gjc <>", value, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcGreaterThan(String value) {
            addCriterion("gjc >", value, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcGreaterThanOrEqualTo(String value) {
            addCriterion("gjc >=", value, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcLessThan(String value) {
            addCriterion("gjc <", value, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcLessThanOrEqualTo(String value) {
            addCriterion("gjc <=", value, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcLike(String value) {
            addCriterion("gjc like", value, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcNotLike(String value) {
            addCriterion("gjc not like", value, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcIn(List<String> values) {
            addCriterion("gjc in", values, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcNotIn(List<String> values) {
            addCriterion("gjc not in", values, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcBetween(String value1, String value2) {
            addCriterion("gjc between", value1, value2, "gjc");
            return (Criteria) this;
        }

        public Criteria andGjcNotBetween(String value1, String value2) {
            addCriterion("gjc not between", value1, value2, "gjc");
            return (Criteria) this;
        }

        public Criteria andZyIsNull() {
            addCriterion("zy is null");
            return (Criteria) this;
        }

        public Criteria andZyIsNotNull() {
            addCriterion("zy is not null");
            return (Criteria) this;
        }

        public Criteria andZyEqualTo(String value) {
            addCriterion("zy =", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotEqualTo(String value) {
            addCriterion("zy <>", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyGreaterThan(String value) {
            addCriterion("zy >", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyGreaterThanOrEqualTo(String value) {
            addCriterion("zy >=", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyLessThan(String value) {
            addCriterion("zy <", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyLessThanOrEqualTo(String value) {
            addCriterion("zy <=", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyLike(String value) {
            addCriterion("zy like", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotLike(String value) {
            addCriterion("zy not like", value, "zy");
            return (Criteria) this;
        }

        public Criteria andZyIn(List<String> values) {
            addCriterion("zy in", values, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotIn(List<String> values) {
            addCriterion("zy not in", values, "zy");
            return (Criteria) this;
        }

        public Criteria andZyBetween(String value1, String value2) {
            addCriterion("zy between", value1, value2, "zy");
            return (Criteria) this;
        }

        public Criteria andZyNotBetween(String value1, String value2) {
            addCriterion("zy not between", value1, value2, "zy");
            return (Criteria) this;
        }

        public Criteria andSltIsNull() {
            addCriterion("slt is null");
            return (Criteria) this;
        }

        public Criteria andSltIsNotNull() {
            addCriterion("slt is not null");
            return (Criteria) this;
        }

        public Criteria andSltEqualTo(String value) {
            addCriterion("slt =", value, "slt");
            return (Criteria) this;
        }

        public Criteria andSltNotEqualTo(String value) {
            addCriterion("slt <>", value, "slt");
            return (Criteria) this;
        }

        public Criteria andSltGreaterThan(String value) {
            addCriterion("slt >", value, "slt");
            return (Criteria) this;
        }

        public Criteria andSltGreaterThanOrEqualTo(String value) {
            addCriterion("slt >=", value, "slt");
            return (Criteria) this;
        }

        public Criteria andSltLessThan(String value) {
            addCriterion("slt <", value, "slt");
            return (Criteria) this;
        }

        public Criteria andSltLessThanOrEqualTo(String value) {
            addCriterion("slt <=", value, "slt");
            return (Criteria) this;
        }

        public Criteria andSltLike(String value) {
            addCriterion("slt like", value, "slt");
            return (Criteria) this;
        }

        public Criteria andSltNotLike(String value) {
            addCriterion("slt not like", value, "slt");
            return (Criteria) this;
        }

        public Criteria andSltIn(List<String> values) {
            addCriterion("slt in", values, "slt");
            return (Criteria) this;
        }

        public Criteria andSltNotIn(List<String> values) {
            addCriterion("slt not in", values, "slt");
            return (Criteria) this;
        }

        public Criteria andSltBetween(String value1, String value2) {
            addCriterion("slt between", value1, value2, "slt");
            return (Criteria) this;
        }

        public Criteria andSltNotBetween(String value1, String value2) {
            addCriterion("slt not between", value1, value2, "slt");
            return (Criteria) this;
        }

        public Criteria andTzljIsNull() {
            addCriterion("tzlj is null");
            return (Criteria) this;
        }

        public Criteria andTzljIsNotNull() {
            addCriterion("tzlj is not null");
            return (Criteria) this;
        }

        public Criteria andTzljEqualTo(String value) {
            addCriterion("tzlj =", value, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljNotEqualTo(String value) {
            addCriterion("tzlj <>", value, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljGreaterThan(String value) {
            addCriterion("tzlj >", value, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljGreaterThanOrEqualTo(String value) {
            addCriterion("tzlj >=", value, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljLessThan(String value) {
            addCriterion("tzlj <", value, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljLessThanOrEqualTo(String value) {
            addCriterion("tzlj <=", value, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljLike(String value) {
            addCriterion("tzlj like", value, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljNotLike(String value) {
            addCriterion("tzlj not like", value, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljIn(List<String> values) {
            addCriterion("tzlj in", values, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljNotIn(List<String> values) {
            addCriterion("tzlj not in", values, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljBetween(String value1, String value2) {
            addCriterion("tzlj between", value1, value2, "tzlj");
            return (Criteria) this;
        }

        public Criteria andTzljNotBetween(String value1, String value2) {
            addCriterion("tzlj not between", value1, value2, "tzlj");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}