package cn.gov.model;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.bt
     *
     * @mbggenerated
     */
    private String bt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.lb
     *
     * @mbggenerated
     */
    private Integer lb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.lrrq
     *
     * @mbggenerated
     */
    private String lrrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.xxly
     *
     * @mbggenerated
     */
    private String xxly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.gg
     *
     * @mbggenerated
     */
    private String gg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.sftj
     *
     * @mbggenerated
     */
    private Boolean sftj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.sfxs
     *
     * @mbggenerated
     */
    private Boolean sfxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.ydcs
     *
     * @mbggenerated
     */
    private Integer ydcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.nr
     *
     * @mbggenerated
     */
    private String nr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.bt
     *
     * @return the value of article.bt
     *
     * @mbggenerated
     */
    public String getBt() {
        return bt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.bt
     *
     * @param bt the value for article.bt
     *
     * @mbggenerated
     */
    public void setBt(String bt) {
        this.bt = bt == null ? null : bt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.lb
     *
     * @return the value of article.lb
     *
     * @mbggenerated
     */
    public Integer getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.lb
     *
     * @param lb the value for article.lb
     *
     * @mbggenerated
     */
    public void setLb(Integer lb) {
        this.lb = lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.lrrq
     *
     * @return the value of article.lrrq
     *
     * @mbggenerated
     */
    public String getLrrq() {
        return lrrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.lrrq
     *
     * @param lrrq the value for article.lrrq
     *
     * @mbggenerated
     */
    public void setLrrq(String lrrq) {
        this.lrrq = lrrq == null ? null : lrrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.xxly
     *
     * @return the value of article.xxly
     *
     * @mbggenerated
     */
    public String getXxly() {
        return xxly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.xxly
     *
     * @param xxly the value for article.xxly
     *
     * @mbggenerated
     */
    public void setXxly(String xxly) {
        this.xxly = xxly == null ? null : xxly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.gg
     *
     * @return the value of article.gg
     *
     * @mbggenerated
     */
    public String getGg() {
        return gg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.gg
     *
     * @param gg the value for article.gg
     *
     * @mbggenerated
     */
    public void setGg(String gg) {
        this.gg = gg == null ? null : gg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.sftj
     *
     * @return the value of article.sftj
     *
     * @mbggenerated
     */
    public Boolean getSftj() {
        return sftj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.sftj
     *
     * @param sftj the value for article.sftj
     *
     * @mbggenerated
     */
    public void setSftj(Boolean sftj) {
        this.sftj = sftj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.sfxs
     *
     * @return the value of article.sfxs
     *
     * @mbggenerated
     */
    public Boolean getSfxs() {
        return sfxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.sfxs
     *
     * @param sfxs the value for article.sfxs
     *
     * @mbggenerated
     */
    public void setSfxs(Boolean sfxs) {
        this.sfxs = sfxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.ydcs
     *
     * @return the value of article.ydcs
     *
     * @mbggenerated
     */
    public Integer getYdcs() {
        return ydcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.ydcs
     *
     * @param ydcs the value for article.ydcs
     *
     * @mbggenerated
     */
    public void setYdcs(Integer ydcs) {
        this.ydcs = ydcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.nr
     *
     * @return the value of article.nr
     *
     * @mbggenerated
     */
    public String getNr() {
        return nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.nr
     *
     * @param nr the value for article.nr
     *
     * @mbggenerated
     */
    public void setNr(String nr) {
        this.nr = nr == null ? null : nr.trim();
    }
}