package cn.gov.model;

import java.util.ArrayList;
import java.util.List;

public class ConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public ConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDomainNameIsNull() {
            addCriterion("domain_name is null");
            return (Criteria) this;
        }

        public Criteria andDomainNameIsNotNull() {
            addCriterion("domain_name is not null");
            return (Criteria) this;
        }

        public Criteria andDomainNameEqualTo(String value) {
            addCriterion("domain_name =", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameNotEqualTo(String value) {
            addCriterion("domain_name <>", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameGreaterThan(String value) {
            addCriterion("domain_name >", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameGreaterThanOrEqualTo(String value) {
            addCriterion("domain_name >=", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameLessThan(String value) {
            addCriterion("domain_name <", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameLessThanOrEqualTo(String value) {
            addCriterion("domain_name <=", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameLike(String value) {
            addCriterion("domain_name like", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameNotLike(String value) {
            addCriterion("domain_name not like", value, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameIn(List<String> values) {
            addCriterion("domain_name in", values, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameNotIn(List<String> values) {
            addCriterion("domain_name not in", values, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameBetween(String value1, String value2) {
            addCriterion("domain_name between", value1, value2, "domainName");
            return (Criteria) this;
        }

        public Criteria andDomainNameNotBetween(String value1, String value2) {
            addCriterion("domain_name not between", value1, value2, "domainName");
            return (Criteria) this;
        }

        public Criteria andFilingNumIsNull() {
            addCriterion("filing_num is null");
            return (Criteria) this;
        }

        public Criteria andFilingNumIsNotNull() {
            addCriterion("filing_num is not null");
            return (Criteria) this;
        }

        public Criteria andFilingNumEqualTo(String value) {
            addCriterion("filing_num =", value, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumNotEqualTo(String value) {
            addCriterion("filing_num <>", value, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumGreaterThan(String value) {
            addCriterion("filing_num >", value, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumGreaterThanOrEqualTo(String value) {
            addCriterion("filing_num >=", value, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumLessThan(String value) {
            addCriterion("filing_num <", value, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumLessThanOrEqualTo(String value) {
            addCriterion("filing_num <=", value, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumLike(String value) {
            addCriterion("filing_num like", value, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumNotLike(String value) {
            addCriterion("filing_num not like", value, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumIn(List<String> values) {
            addCriterion("filing_num in", values, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumNotIn(List<String> values) {
            addCriterion("filing_num not in", values, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumBetween(String value1, String value2) {
            addCriterion("filing_num between", value1, value2, "filingNum");
            return (Criteria) this;
        }

        public Criteria andFilingNumNotBetween(String value1, String value2) {
            addCriterion("filing_num not between", value1, value2, "filingNum");
            return (Criteria) this;
        }

        public Criteria andCopyrightIsNull() {
            addCriterion("copyright is null");
            return (Criteria) this;
        }

        public Criteria andCopyrightIsNotNull() {
            addCriterion("copyright is not null");
            return (Criteria) this;
        }

        public Criteria andCopyrightEqualTo(String value) {
            addCriterion("copyright =", value, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightNotEqualTo(String value) {
            addCriterion("copyright <>", value, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightGreaterThan(String value) {
            addCriterion("copyright >", value, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightGreaterThanOrEqualTo(String value) {
            addCriterion("copyright >=", value, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightLessThan(String value) {
            addCriterion("copyright <", value, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightLessThanOrEqualTo(String value) {
            addCriterion("copyright <=", value, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightLike(String value) {
            addCriterion("copyright like", value, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightNotLike(String value) {
            addCriterion("copyright not like", value, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightIn(List<String> values) {
            addCriterion("copyright in", values, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightNotIn(List<String> values) {
            addCriterion("copyright not in", values, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightBetween(String value1, String value2) {
            addCriterion("copyright between", value1, value2, "copyright");
            return (Criteria) this;
        }

        public Criteria andCopyrightNotBetween(String value1, String value2) {
            addCriterion("copyright not between", value1, value2, "copyright");
            return (Criteria) this;
        }

        public Criteria andToggleIsNull() {
            addCriterion("toggle is null");
            return (Criteria) this;
        }

        public Criteria andToggleIsNotNull() {
            addCriterion("toggle is not null");
            return (Criteria) this;
        }

        public Criteria andToggleEqualTo(Boolean value) {
            addCriterion("toggle =", value, "toggle");
            return (Criteria) this;
        }

        public Criteria andToggleNotEqualTo(Boolean value) {
            addCriterion("toggle <>", value, "toggle");
            return (Criteria) this;
        }

        public Criteria andToggleGreaterThan(Boolean value) {
            addCriterion("toggle >", value, "toggle");
            return (Criteria) this;
        }

        public Criteria andToggleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("toggle >=", value, "toggle");
            return (Criteria) this;
        }

        public Criteria andToggleLessThan(Boolean value) {
            addCriterion("toggle <", value, "toggle");
            return (Criteria) this;
        }

        public Criteria andToggleLessThanOrEqualTo(Boolean value) {
            addCriterion("toggle <=", value, "toggle");
            return (Criteria) this;
        }

        public Criteria andToggleIn(List<Boolean> values) {
            addCriterion("toggle in", values, "toggle");
            return (Criteria) this;
        }

        public Criteria andToggleNotIn(List<Boolean> values) {
            addCriterion("toggle not in", values, "toggle");
            return (Criteria) this;
        }

        public Criteria andToggleBetween(Boolean value1, Boolean value2) {
            addCriterion("toggle between", value1, value2, "toggle");
            return (Criteria) this;
        }

        public Criteria andToggleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("toggle not between", value1, value2, "toggle");
            return (Criteria) this;
        }

        public Criteria andCloseInfoIsNull() {
            addCriterion("close_info is null");
            return (Criteria) this;
        }

        public Criteria andCloseInfoIsNotNull() {
            addCriterion("close_info is not null");
            return (Criteria) this;
        }

        public Criteria andCloseInfoEqualTo(String value) {
            addCriterion("close_info =", value, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoNotEqualTo(String value) {
            addCriterion("close_info <>", value, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoGreaterThan(String value) {
            addCriterion("close_info >", value, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoGreaterThanOrEqualTo(String value) {
            addCriterion("close_info >=", value, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoLessThan(String value) {
            addCriterion("close_info <", value, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoLessThanOrEqualTo(String value) {
            addCriterion("close_info <=", value, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoLike(String value) {
            addCriterion("close_info like", value, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoNotLike(String value) {
            addCriterion("close_info not like", value, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoIn(List<String> values) {
            addCriterion("close_info in", values, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoNotIn(List<String> values) {
            addCriterion("close_info not in", values, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoBetween(String value1, String value2) {
            addCriterion("close_info between", value1, value2, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andCloseInfoNotBetween(String value1, String value2) {
            addCriterion("close_info not between", value1, value2, "closeInfo");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("keyword is null");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("keyword is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("keyword =", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("keyword <>", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("keyword >", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("keyword >=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("keyword <", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("keyword <=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("keyword like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("keyword not like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordIn(List<String> values) {
            addCriterion("keyword in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotIn(List<String> values) {
            addCriterion("keyword not in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("keyword between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("keyword not between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andPreventCopyIsNull() {
            addCriterion("prevent_copy is null");
            return (Criteria) this;
        }

        public Criteria andPreventCopyIsNotNull() {
            addCriterion("prevent_copy is not null");
            return (Criteria) this;
        }

        public Criteria andPreventCopyEqualTo(Boolean value) {
            addCriterion("prevent_copy =", value, "preventCopy");
            return (Criteria) this;
        }

        public Criteria andPreventCopyNotEqualTo(Boolean value) {
            addCriterion("prevent_copy <>", value, "preventCopy");
            return (Criteria) this;
        }

        public Criteria andPreventCopyGreaterThan(Boolean value) {
            addCriterion("prevent_copy >", value, "preventCopy");
            return (Criteria) this;
        }

        public Criteria andPreventCopyGreaterThanOrEqualTo(Boolean value) {
            addCriterion("prevent_copy >=", value, "preventCopy");
            return (Criteria) this;
        }

        public Criteria andPreventCopyLessThan(Boolean value) {
            addCriterion("prevent_copy <", value, "preventCopy");
            return (Criteria) this;
        }

        public Criteria andPreventCopyLessThanOrEqualTo(Boolean value) {
            addCriterion("prevent_copy <=", value, "preventCopy");
            return (Criteria) this;
        }

        public Criteria andPreventCopyIn(List<Boolean> values) {
            addCriterion("prevent_copy in", values, "preventCopy");
            return (Criteria) this;
        }

        public Criteria andPreventCopyNotIn(List<Boolean> values) {
            addCriterion("prevent_copy not in", values, "preventCopy");
            return (Criteria) this;
        }

        public Criteria andPreventCopyBetween(Boolean value1, Boolean value2) {
            addCriterion("prevent_copy between", value1, value2, "preventCopy");
            return (Criteria) this;
        }

        public Criteria andPreventCopyNotBetween(Boolean value1, Boolean value2) {
            addCriterion("prevent_copy not between", value1, value2, "preventCopy");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}