package cn.gov.model;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.domain_name
     *
     * @mbggenerated
     */
    private String domainName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.filing_num
     *
     * @mbggenerated
     */
    private String filingNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.copyright
     *
     * @mbggenerated
     */
    private String copyright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.toggle
     *
     * @mbggenerated
     */
    private Boolean toggle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.close_info
     *
     * @mbggenerated
     */
    private String closeInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.keyword
     *
     * @mbggenerated
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.prevent_copy
     *
     * @mbggenerated
     */
    private Boolean preventCopy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.name
     *
     * @return the value of config.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.name
     *
     * @param name the value for config.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.domain_name
     *
     * @return the value of config.domain_name
     *
     * @mbggenerated
     */
    public String getDomainName() {
        return domainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.domain_name
     *
     * @param domainName the value for config.domain_name
     *
     * @mbggenerated
     */
    public void setDomainName(String domainName) {
        this.domainName = domainName == null ? null : domainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.filing_num
     *
     * @return the value of config.filing_num
     *
     * @mbggenerated
     */
    public String getFilingNum() {
        return filingNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.filing_num
     *
     * @param filingNum the value for config.filing_num
     *
     * @mbggenerated
     */
    public void setFilingNum(String filingNum) {
        this.filingNum = filingNum == null ? null : filingNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.copyright
     *
     * @return the value of config.copyright
     *
     * @mbggenerated
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.copyright
     *
     * @param copyright the value for config.copyright
     *
     * @mbggenerated
     */
    public void setCopyright(String copyright) {
        this.copyright = copyright == null ? null : copyright.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.toggle
     *
     * @return the value of config.toggle
     *
     * @mbggenerated
     */
    public Boolean getToggle() {
        return toggle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.toggle
     *
     * @param toggle the value for config.toggle
     *
     * @mbggenerated
     */
    public void setToggle(Boolean toggle) {
        this.toggle = toggle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.close_info
     *
     * @return the value of config.close_info
     *
     * @mbggenerated
     */
    public String getCloseInfo() {
        return closeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.close_info
     *
     * @param closeInfo the value for config.close_info
     *
     * @mbggenerated
     */
    public void setCloseInfo(String closeInfo) {
        this.closeInfo = closeInfo == null ? null : closeInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.title
     *
     * @return the value of config.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.title
     *
     * @param title the value for config.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.keyword
     *
     * @return the value of config.keyword
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.keyword
     *
     * @param keyword the value for config.keyword
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.description
     *
     * @return the value of config.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.description
     *
     * @param description the value for config.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.prevent_copy
     *
     * @return the value of config.prevent_copy
     *
     * @mbggenerated
     */
    public Boolean getPreventCopy() {
        return preventCopy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.prevent_copy
     *
     * @param preventCopy the value for config.prevent_copy
     *
     * @mbggenerated
     */
    public void setPreventCopy(Boolean preventCopy) {
        this.preventCopy = preventCopy;
    }
}