package cn.gov.model;

import java.util.Date;

public class InspectReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.report_name
     *
     * @mbggenerated
     */
    private String reportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.report_contact
     *
     * @mbggenerated
     */
    private String reportContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.report_condition
     *
     * @mbggenerated
     */
    private String reportCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.reported_name
     *
     * @mbggenerated
     */
    private String reportedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.reported_condition
     *
     * @mbggenerated
     */
    private String reportedCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.problem
     *
     * @mbggenerated
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.doc
     *
     * @mbggenerated
     */
    private String doc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.inspect_id
     *
     * @mbggenerated
     */
    private Integer inspectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_report.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.id
     *
     * @return the value of inspect_report.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.id
     *
     * @param id the value for inspect_report.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.report_name
     *
     * @return the value of inspect_report.report_name
     *
     * @mbggenerated
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.report_name
     *
     * @param reportName the value for inspect_report.report_name
     *
     * @mbggenerated
     */
    public void setReportName(String reportName) {
        this.reportName = reportName == null ? null : reportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.report_contact
     *
     * @return the value of inspect_report.report_contact
     *
     * @mbggenerated
     */
    public String getReportContact() {
        return reportContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.report_contact
     *
     * @param reportContact the value for inspect_report.report_contact
     *
     * @mbggenerated
     */
    public void setReportContact(String reportContact) {
        this.reportContact = reportContact == null ? null : reportContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.report_condition
     *
     * @return the value of inspect_report.report_condition
     *
     * @mbggenerated
     */
    public String getReportCondition() {
        return reportCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.report_condition
     *
     * @param reportCondition the value for inspect_report.report_condition
     *
     * @mbggenerated
     */
    public void setReportCondition(String reportCondition) {
        this.reportCondition = reportCondition == null ? null : reportCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.reported_name
     *
     * @return the value of inspect_report.reported_name
     *
     * @mbggenerated
     */
    public String getReportedName() {
        return reportedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.reported_name
     *
     * @param reportedName the value for inspect_report.reported_name
     *
     * @mbggenerated
     */
    public void setReportedName(String reportedName) {
        this.reportedName = reportedName == null ? null : reportedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.reported_condition
     *
     * @return the value of inspect_report.reported_condition
     *
     * @mbggenerated
     */
    public String getReportedCondition() {
        return reportedCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.reported_condition
     *
     * @param reportedCondition the value for inspect_report.reported_condition
     *
     * @mbggenerated
     */
    public void setReportedCondition(String reportedCondition) {
        this.reportedCondition = reportedCondition == null ? null : reportedCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.title
     *
     * @return the value of inspect_report.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.title
     *
     * @param title the value for inspect_report.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.problem
     *
     * @return the value of inspect_report.problem
     *
     * @mbggenerated
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.problem
     *
     * @param problem the value for inspect_report.problem
     *
     * @mbggenerated
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.doc
     *
     * @return the value of inspect_report.doc
     *
     * @mbggenerated
     */
    public String getDoc() {
        return doc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.doc
     *
     * @param doc the value for inspect_report.doc
     *
     * @mbggenerated
     */
    public void setDoc(String doc) {
        this.doc = doc == null ? null : doc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.inspect_id
     *
     * @return the value of inspect_report.inspect_id
     *
     * @mbggenerated
     */
    public Integer getInspectId() {
        return inspectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.inspect_id
     *
     * @param inspectId the value for inspect_report.inspect_id
     *
     * @mbggenerated
     */
    public void setInspectId(Integer inspectId) {
        this.inspectId = inspectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.date
     *
     * @return the value of inspect_report.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.date
     *
     * @param date the value for inspect_report.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_report.ip
     *
     * @return the value of inspect_report.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_report.ip
     *
     * @param ip the value for inspect_report.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}