package cn.gov.model;

import java.util.Date;

public class MessageReply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_reply.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_reply.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_reply.message_id
     *
     * @mbggenerated
     */
    private Integer messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message_reply.reply
     *
     * @mbggenerated
     */
    private String reply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_reply.id
     *
     * @return the value of message_reply.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_reply.id
     *
     * @param id the value for message_reply.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_reply.date
     *
     * @return the value of message_reply.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_reply.date
     *
     * @param date the value for message_reply.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_reply.message_id
     *
     * @return the value of message_reply.message_id
     *
     * @mbggenerated
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_reply.message_id
     *
     * @param messageId the value for message_reply.message_id
     *
     * @mbggenerated
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message_reply.reply
     *
     * @return the value of message_reply.reply
     *
     * @mbggenerated
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message_reply.reply
     *
     * @param reply the value for message_reply.reply
     *
     * @mbggenerated
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }
}