package cn.gov.model;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.bt
     *
     * @mbggenerated
     */
    private String bt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.rq
     *
     * @mbggenerated
     */
    private Date rq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.nr
     *
     * @mbggenerated
     */
    private String nr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.ip
     *
     * @return the value of message.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.ip
     *
     * @param ip the value for message.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.bt
     *
     * @return the value of message.bt
     *
     * @mbggenerated
     */
    public String getBt() {
        return bt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.bt
     *
     * @param bt the value for message.bt
     *
     * @mbggenerated
     */
    public void setBt(String bt) {
        this.bt = bt == null ? null : bt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.rq
     *
     * @return the value of message.rq
     *
     * @mbggenerated
     */
    public Date getRq() {
        return rq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.rq
     *
     * @param rq the value for message.rq
     *
     * @mbggenerated
     */
    public void setRq(Date rq) {
        this.rq = rq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.nr
     *
     * @return the value of message.nr
     *
     * @mbggenerated
     */
    public String getNr() {
        return nr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.nr
     *
     * @param nr the value for message.nr
     *
     * @mbggenerated
     */
    public void setNr(String nr) {
        this.nr = nr == null ? null : nr.trim();
    }
}