package cn.gov.model;

import java.util.Date;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.report_name
     *
     * @mbggenerated
     */
    private String reportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.report_contact
     *
     * @mbggenerated
     */
    private String reportContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.report_condition
     *
     * @mbggenerated
     */
    private String reportCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.reported_name
     *
     * @mbggenerated
     */
    private String reportedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.reported_condition
     *
     * @mbggenerated
     */
    private String reportedCondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.problem
     *
     * @mbggenerated
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.doc
     *
     * @mbggenerated
     */
    private String doc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.report_name
     *
     * @return the value of report.report_name
     *
     * @mbggenerated
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.report_name
     *
     * @param reportName the value for report.report_name
     *
     * @mbggenerated
     */
    public void setReportName(String reportName) {
        this.reportName = reportName == null ? null : reportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.report_contact
     *
     * @return the value of report.report_contact
     *
     * @mbggenerated
     */
    public String getReportContact() {
        return reportContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.report_contact
     *
     * @param reportContact the value for report.report_contact
     *
     * @mbggenerated
     */
    public void setReportContact(String reportContact) {
        this.reportContact = reportContact == null ? null : reportContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.report_condition
     *
     * @return the value of report.report_condition
     *
     * @mbggenerated
     */
    public String getReportCondition() {
        return reportCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.report_condition
     *
     * @param reportCondition the value for report.report_condition
     *
     * @mbggenerated
     */
    public void setReportCondition(String reportCondition) {
        this.reportCondition = reportCondition == null ? null : reportCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.reported_name
     *
     * @return the value of report.reported_name
     *
     * @mbggenerated
     */
    public String getReportedName() {
        return reportedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.reported_name
     *
     * @param reportedName the value for report.reported_name
     *
     * @mbggenerated
     */
    public void setReportedName(String reportedName) {
        this.reportedName = reportedName == null ? null : reportedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.reported_condition
     *
     * @return the value of report.reported_condition
     *
     * @mbggenerated
     */
    public String getReportedCondition() {
        return reportedCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.reported_condition
     *
     * @param reportedCondition the value for report.reported_condition
     *
     * @mbggenerated
     */
    public void setReportedCondition(String reportedCondition) {
        this.reportedCondition = reportedCondition == null ? null : reportedCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.title
     *
     * @return the value of report.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.title
     *
     * @param title the value for report.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.problem
     *
     * @return the value of report.problem
     *
     * @mbggenerated
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.problem
     *
     * @param problem the value for report.problem
     *
     * @mbggenerated
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.doc
     *
     * @return the value of report.doc
     *
     * @mbggenerated
     */
    public String getDoc() {
        return doc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.doc
     *
     * @param doc the value for report.doc
     *
     * @mbggenerated
     */
    public void setDoc(String doc) {
        this.doc = doc == null ? null : doc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.date
     *
     * @return the value of report.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.date
     *
     * @param date the value for report.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.ip
     *
     * @return the value of report.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.ip
     *
     * @param ip the value for report.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }
}