package cn.gov.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReportMsgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public ReportMsgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReportNameIsNull() {
            addCriterion("report_name is null");
            return (Criteria) this;
        }

        public Criteria andReportNameIsNotNull() {
            addCriterion("report_name is not null");
            return (Criteria) this;
        }

        public Criteria andReportNameEqualTo(String value) {
            addCriterion("report_name =", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotEqualTo(String value) {
            addCriterion("report_name <>", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameGreaterThan(String value) {
            addCriterion("report_name >", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameGreaterThanOrEqualTo(String value) {
            addCriterion("report_name >=", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameLessThan(String value) {
            addCriterion("report_name <", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameLessThanOrEqualTo(String value) {
            addCriterion("report_name <=", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameLike(String value) {
            addCriterion("report_name like", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotLike(String value) {
            addCriterion("report_name not like", value, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameIn(List<String> values) {
            addCriterion("report_name in", values, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotIn(List<String> values) {
            addCriterion("report_name not in", values, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameBetween(String value1, String value2) {
            addCriterion("report_name between", value1, value2, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportNameNotBetween(String value1, String value2) {
            addCriterion("report_name not between", value1, value2, "reportName");
            return (Criteria) this;
        }

        public Criteria andReportIdIsNull() {
            addCriterion("report_id is null");
            return (Criteria) this;
        }

        public Criteria andReportIdIsNotNull() {
            addCriterion("report_id is not null");
            return (Criteria) this;
        }

        public Criteria andReportIdEqualTo(String value) {
            addCriterion("report_id =", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdNotEqualTo(String value) {
            addCriterion("report_id <>", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdGreaterThan(String value) {
            addCriterion("report_id >", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdGreaterThanOrEqualTo(String value) {
            addCriterion("report_id >=", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdLessThan(String value) {
            addCriterion("report_id <", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdLessThanOrEqualTo(String value) {
            addCriterion("report_id <=", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdLike(String value) {
            addCriterion("report_id like", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdNotLike(String value) {
            addCriterion("report_id not like", value, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdIn(List<String> values) {
            addCriterion("report_id in", values, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdNotIn(List<String> values) {
            addCriterion("report_id not in", values, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdBetween(String value1, String value2) {
            addCriterion("report_id between", value1, value2, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportIdNotBetween(String value1, String value2) {
            addCriterion("report_id not between", value1, value2, "reportId");
            return (Criteria) this;
        }

        public Criteria andReportContactIsNull() {
            addCriterion("report_contact is null");
            return (Criteria) this;
        }

        public Criteria andReportContactIsNotNull() {
            addCriterion("report_contact is not null");
            return (Criteria) this;
        }

        public Criteria andReportContactEqualTo(String value) {
            addCriterion("report_contact =", value, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactNotEqualTo(String value) {
            addCriterion("report_contact <>", value, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactGreaterThan(String value) {
            addCriterion("report_contact >", value, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactGreaterThanOrEqualTo(String value) {
            addCriterion("report_contact >=", value, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactLessThan(String value) {
            addCriterion("report_contact <", value, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactLessThanOrEqualTo(String value) {
            addCriterion("report_contact <=", value, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactLike(String value) {
            addCriterion("report_contact like", value, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactNotLike(String value) {
            addCriterion("report_contact not like", value, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactIn(List<String> values) {
            addCriterion("report_contact in", values, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactNotIn(List<String> values) {
            addCriterion("report_contact not in", values, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactBetween(String value1, String value2) {
            addCriterion("report_contact between", value1, value2, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportContactNotBetween(String value1, String value2) {
            addCriterion("report_contact not between", value1, value2, "reportContact");
            return (Criteria) this;
        }

        public Criteria andReportStatusIsNull() {
            addCriterion("report_status is null");
            return (Criteria) this;
        }

        public Criteria andReportStatusIsNotNull() {
            addCriterion("report_status is not null");
            return (Criteria) this;
        }

        public Criteria andReportStatusEqualTo(String value) {
            addCriterion("report_status =", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusNotEqualTo(String value) {
            addCriterion("report_status <>", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusGreaterThan(String value) {
            addCriterion("report_status >", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusGreaterThanOrEqualTo(String value) {
            addCriterion("report_status >=", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusLessThan(String value) {
            addCriterion("report_status <", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusLessThanOrEqualTo(String value) {
            addCriterion("report_status <=", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusLike(String value) {
            addCriterion("report_status like", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusNotLike(String value) {
            addCriterion("report_status not like", value, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusIn(List<String> values) {
            addCriterion("report_status in", values, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusNotIn(List<String> values) {
            addCriterion("report_status not in", values, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusBetween(String value1, String value2) {
            addCriterion("report_status between", value1, value2, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportStatusNotBetween(String value1, String value2) {
            addCriterion("report_status not between", value1, value2, "reportStatus");
            return (Criteria) this;
        }

        public Criteria andReportAddressIsNull() {
            addCriterion("report_address is null");
            return (Criteria) this;
        }

        public Criteria andReportAddressIsNotNull() {
            addCriterion("report_address is not null");
            return (Criteria) this;
        }

        public Criteria andReportAddressEqualTo(String value) {
            addCriterion("report_address =", value, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressNotEqualTo(String value) {
            addCriterion("report_address <>", value, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressGreaterThan(String value) {
            addCriterion("report_address >", value, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressGreaterThanOrEqualTo(String value) {
            addCriterion("report_address >=", value, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressLessThan(String value) {
            addCriterion("report_address <", value, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressLessThanOrEqualTo(String value) {
            addCriterion("report_address <=", value, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressLike(String value) {
            addCriterion("report_address like", value, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressNotLike(String value) {
            addCriterion("report_address not like", value, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressIn(List<String> values) {
            addCriterion("report_address in", values, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressNotIn(List<String> values) {
            addCriterion("report_address not in", values, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressBetween(String value1, String value2) {
            addCriterion("report_address between", value1, value2, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportAddressNotBetween(String value1, String value2) {
            addCriterion("report_address not between", value1, value2, "reportAddress");
            return (Criteria) this;
        }

        public Criteria andReportLevelIsNull() {
            addCriterion("report_level is null");
            return (Criteria) this;
        }

        public Criteria andReportLevelIsNotNull() {
            addCriterion("report_level is not null");
            return (Criteria) this;
        }

        public Criteria andReportLevelEqualTo(String value) {
            addCriterion("report_level =", value, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelNotEqualTo(String value) {
            addCriterion("report_level <>", value, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelGreaterThan(String value) {
            addCriterion("report_level >", value, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelGreaterThanOrEqualTo(String value) {
            addCriterion("report_level >=", value, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelLessThan(String value) {
            addCriterion("report_level <", value, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelLessThanOrEqualTo(String value) {
            addCriterion("report_level <=", value, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelLike(String value) {
            addCriterion("report_level like", value, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelNotLike(String value) {
            addCriterion("report_level not like", value, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelIn(List<String> values) {
            addCriterion("report_level in", values, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelNotIn(List<String> values) {
            addCriterion("report_level not in", values, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelBetween(String value1, String value2) {
            addCriterion("report_level between", value1, value2, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportLevelNotBetween(String value1, String value2) {
            addCriterion("report_level not between", value1, value2, "reportLevel");
            return (Criteria) this;
        }

        public Criteria andReportedNameIsNull() {
            addCriterion("reported_name is null");
            return (Criteria) this;
        }

        public Criteria andReportedNameIsNotNull() {
            addCriterion("reported_name is not null");
            return (Criteria) this;
        }

        public Criteria andReportedNameEqualTo(String value) {
            addCriterion("reported_name =", value, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameNotEqualTo(String value) {
            addCriterion("reported_name <>", value, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameGreaterThan(String value) {
            addCriterion("reported_name >", value, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameGreaterThanOrEqualTo(String value) {
            addCriterion("reported_name >=", value, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameLessThan(String value) {
            addCriterion("reported_name <", value, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameLessThanOrEqualTo(String value) {
            addCriterion("reported_name <=", value, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameLike(String value) {
            addCriterion("reported_name like", value, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameNotLike(String value) {
            addCriterion("reported_name not like", value, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameIn(List<String> values) {
            addCriterion("reported_name in", values, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameNotIn(List<String> values) {
            addCriterion("reported_name not in", values, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameBetween(String value1, String value2) {
            addCriterion("reported_name between", value1, value2, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedNameNotBetween(String value1, String value2) {
            addCriterion("reported_name not between", value1, value2, "reportedName");
            return (Criteria) this;
        }

        public Criteria andReportedOrgIsNull() {
            addCriterion("reported_org is null");
            return (Criteria) this;
        }

        public Criteria andReportedOrgIsNotNull() {
            addCriterion("reported_org is not null");
            return (Criteria) this;
        }

        public Criteria andReportedOrgEqualTo(String value) {
            addCriterion("reported_org =", value, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgNotEqualTo(String value) {
            addCriterion("reported_org <>", value, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgGreaterThan(String value) {
            addCriterion("reported_org >", value, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgGreaterThanOrEqualTo(String value) {
            addCriterion("reported_org >=", value, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgLessThan(String value) {
            addCriterion("reported_org <", value, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgLessThanOrEqualTo(String value) {
            addCriterion("reported_org <=", value, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgLike(String value) {
            addCriterion("reported_org like", value, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgNotLike(String value) {
            addCriterion("reported_org not like", value, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgIn(List<String> values) {
            addCriterion("reported_org in", values, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgNotIn(List<String> values) {
            addCriterion("reported_org not in", values, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgBetween(String value1, String value2) {
            addCriterion("reported_org between", value1, value2, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedOrgNotBetween(String value1, String value2) {
            addCriterion("reported_org not between", value1, value2, "reportedOrg");
            return (Criteria) this;
        }

        public Criteria andReportedPostIsNull() {
            addCriterion("reported_post is null");
            return (Criteria) this;
        }

        public Criteria andReportedPostIsNotNull() {
            addCriterion("reported_post is not null");
            return (Criteria) this;
        }

        public Criteria andReportedPostEqualTo(String value) {
            addCriterion("reported_post =", value, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostNotEqualTo(String value) {
            addCriterion("reported_post <>", value, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostGreaterThan(String value) {
            addCriterion("reported_post >", value, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostGreaterThanOrEqualTo(String value) {
            addCriterion("reported_post >=", value, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostLessThan(String value) {
            addCriterion("reported_post <", value, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostLessThanOrEqualTo(String value) {
            addCriterion("reported_post <=", value, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostLike(String value) {
            addCriterion("reported_post like", value, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostNotLike(String value) {
            addCriterion("reported_post not like", value, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostIn(List<String> values) {
            addCriterion("reported_post in", values, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostNotIn(List<String> values) {
            addCriterion("reported_post not in", values, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostBetween(String value1, String value2) {
            addCriterion("reported_post between", value1, value2, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedPostNotBetween(String value1, String value2) {
            addCriterion("reported_post not between", value1, value2, "reportedPost");
            return (Criteria) this;
        }

        public Criteria andReportedLevelIsNull() {
            addCriterion("reported_level is null");
            return (Criteria) this;
        }

        public Criteria andReportedLevelIsNotNull() {
            addCriterion("reported_level is not null");
            return (Criteria) this;
        }

        public Criteria andReportedLevelEqualTo(String value) {
            addCriterion("reported_level =", value, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelNotEqualTo(String value) {
            addCriterion("reported_level <>", value, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelGreaterThan(String value) {
            addCriterion("reported_level >", value, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelGreaterThanOrEqualTo(String value) {
            addCriterion("reported_level >=", value, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelLessThan(String value) {
            addCriterion("reported_level <", value, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelLessThanOrEqualTo(String value) {
            addCriterion("reported_level <=", value, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelLike(String value) {
            addCriterion("reported_level like", value, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelNotLike(String value) {
            addCriterion("reported_level not like", value, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelIn(List<String> values) {
            addCriterion("reported_level in", values, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelNotIn(List<String> values) {
            addCriterion("reported_level not in", values, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelBetween(String value1, String value2) {
            addCriterion("reported_level between", value1, value2, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andReportedLevelNotBetween(String value1, String value2) {
            addCriterion("reported_level not between", value1, value2, "reportedLevel");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andProblemTypeIsNull() {
            addCriterion("problem_type is null");
            return (Criteria) this;
        }

        public Criteria andProblemTypeIsNotNull() {
            addCriterion("problem_type is not null");
            return (Criteria) this;
        }

        public Criteria andProblemTypeEqualTo(String value) {
            addCriterion("problem_type =", value, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeNotEqualTo(String value) {
            addCriterion("problem_type <>", value, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeGreaterThan(String value) {
            addCriterion("problem_type >", value, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeGreaterThanOrEqualTo(String value) {
            addCriterion("problem_type >=", value, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeLessThan(String value) {
            addCriterion("problem_type <", value, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeLessThanOrEqualTo(String value) {
            addCriterion("problem_type <=", value, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeLike(String value) {
            addCriterion("problem_type like", value, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeNotLike(String value) {
            addCriterion("problem_type not like", value, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeIn(List<String> values) {
            addCriterion("problem_type in", values, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeNotIn(List<String> values) {
            addCriterion("problem_type not in", values, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeBetween(String value1, String value2) {
            addCriterion("problem_type between", value1, value2, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeNotBetween(String value1, String value2) {
            addCriterion("problem_type not between", value1, value2, "problemType");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailIsNull() {
            addCriterion("problem_type_detail is null");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailIsNotNull() {
            addCriterion("problem_type_detail is not null");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailEqualTo(String value) {
            addCriterion("problem_type_detail =", value, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailNotEqualTo(String value) {
            addCriterion("problem_type_detail <>", value, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailGreaterThan(String value) {
            addCriterion("problem_type_detail >", value, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailGreaterThanOrEqualTo(String value) {
            addCriterion("problem_type_detail >=", value, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailLessThan(String value) {
            addCriterion("problem_type_detail <", value, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailLessThanOrEqualTo(String value) {
            addCriterion("problem_type_detail <=", value, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailLike(String value) {
            addCriterion("problem_type_detail like", value, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailNotLike(String value) {
            addCriterion("problem_type_detail not like", value, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailIn(List<String> values) {
            addCriterion("problem_type_detail in", values, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailNotIn(List<String> values) {
            addCriterion("problem_type_detail not in", values, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailBetween(String value1, String value2) {
            addCriterion("problem_type_detail between", value1, value2, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andProblemTypeDetailNotBetween(String value1, String value2) {
            addCriterion("problem_type_detail not between", value1, value2, "problemTypeDetail");
            return (Criteria) this;
        }

        public Criteria andAnswerIsNull() {
            addCriterion("answer is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIsNotNull() {
            addCriterion("answer is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerEqualTo(String value) {
            addCriterion("answer =", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotEqualTo(String value) {
            addCriterion("answer <>", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerGreaterThan(String value) {
            addCriterion("answer >", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("answer >=", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLessThan(String value) {
            addCriterion("answer <", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLessThanOrEqualTo(String value) {
            addCriterion("answer <=", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLike(String value) {
            addCriterion("answer like", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotLike(String value) {
            addCriterion("answer not like", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerIn(List<String> values) {
            addCriterion("answer in", values, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotIn(List<String> values) {
            addCriterion("answer not in", values, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerBetween(String value1, String value2) {
            addCriterion("answer between", value1, value2, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotBetween(String value1, String value2) {
            addCriterion("answer not between", value1, value2, "answer");
            return (Criteria) this;
        }

        public Criteria andAnsweredIsNull() {
            addCriterion("answered is null");
            return (Criteria) this;
        }

        public Criteria andAnsweredIsNotNull() {
            addCriterion("answered is not null");
            return (Criteria) this;
        }

        public Criteria andAnsweredEqualTo(Boolean value) {
            addCriterion("answered =", value, "answered");
            return (Criteria) this;
        }

        public Criteria andAnsweredNotEqualTo(Boolean value) {
            addCriterion("answered <>", value, "answered");
            return (Criteria) this;
        }

        public Criteria andAnsweredGreaterThan(Boolean value) {
            addCriterion("answered >", value, "answered");
            return (Criteria) this;
        }

        public Criteria andAnsweredGreaterThanOrEqualTo(Boolean value) {
            addCriterion("answered >=", value, "answered");
            return (Criteria) this;
        }

        public Criteria andAnsweredLessThan(Boolean value) {
            addCriterion("answered <", value, "answered");
            return (Criteria) this;
        }

        public Criteria andAnsweredLessThanOrEqualTo(Boolean value) {
            addCriterion("answered <=", value, "answered");
            return (Criteria) this;
        }

        public Criteria andAnsweredIn(List<Boolean> values) {
            addCriterion("answered in", values, "answered");
            return (Criteria) this;
        }

        public Criteria andAnsweredNotIn(List<Boolean> values) {
            addCriterion("answered not in", values, "answered");
            return (Criteria) this;
        }

        public Criteria andAnsweredBetween(Boolean value1, Boolean value2) {
            addCriterion("answered between", value1, value2, "answered");
            return (Criteria) this;
        }

        public Criteria andAnsweredNotBetween(Boolean value1, Boolean value2) {
            addCriterion("answered not between", value1, value2, "answered");
            return (Criteria) this;
        }

        public Criteria andSignedIsNull() {
            addCriterion("signed is null");
            return (Criteria) this;
        }

        public Criteria andSignedIsNotNull() {
            addCriterion("signed is not null");
            return (Criteria) this;
        }

        public Criteria andSignedEqualTo(Boolean value) {
            addCriterion("signed =", value, "signed");
            return (Criteria) this;
        }

        public Criteria andSignedNotEqualTo(Boolean value) {
            addCriterion("signed <>", value, "signed");
            return (Criteria) this;
        }

        public Criteria andSignedGreaterThan(Boolean value) {
            addCriterion("signed >", value, "signed");
            return (Criteria) this;
        }

        public Criteria andSignedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("signed >=", value, "signed");
            return (Criteria) this;
        }

        public Criteria andSignedLessThan(Boolean value) {
            addCriterion("signed <", value, "signed");
            return (Criteria) this;
        }

        public Criteria andSignedLessThanOrEqualTo(Boolean value) {
            addCriterion("signed <=", value, "signed");
            return (Criteria) this;
        }

        public Criteria andSignedIn(List<Boolean> values) {
            addCriterion("signed in", values, "signed");
            return (Criteria) this;
        }

        public Criteria andSignedNotIn(List<Boolean> values) {
            addCriterion("signed not in", values, "signed");
            return (Criteria) this;
        }

        public Criteria andSignedBetween(Boolean value1, Boolean value2) {
            addCriterion("signed between", value1, value2, "signed");
            return (Criteria) this;
        }

        public Criteria andSignedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("signed not between", value1, value2, "signed");
            return (Criteria) this;
        }

        public Criteria andOrgIsNull() {
            addCriterion("org is null");
            return (Criteria) this;
        }

        public Criteria andOrgIsNotNull() {
            addCriterion("org is not null");
            return (Criteria) this;
        }

        public Criteria andOrgEqualTo(String value) {
            addCriterion("org =", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotEqualTo(String value) {
            addCriterion("org <>", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgGreaterThan(String value) {
            addCriterion("org >", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgGreaterThanOrEqualTo(String value) {
            addCriterion("org >=", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgLessThan(String value) {
            addCriterion("org <", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgLessThanOrEqualTo(String value) {
            addCriterion("org <=", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgLike(String value) {
            addCriterion("org like", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotLike(String value) {
            addCriterion("org not like", value, "org");
            return (Criteria) this;
        }

        public Criteria andOrgIn(List<String> values) {
            addCriterion("org in", values, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotIn(List<String> values) {
            addCriterion("org not in", values, "org");
            return (Criteria) this;
        }

        public Criteria andOrgBetween(String value1, String value2) {
            addCriterion("org between", value1, value2, "org");
            return (Criteria) this;
        }

        public Criteria andOrgNotBetween(String value1, String value2) {
            addCriterion("org not between", value1, value2, "org");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_msg
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table report_msg
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}