package cn.gov.model;

public class Source {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.mc
     *
     * @mbggenerated
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.px
     *
     * @mbggenerated
     */
    private Integer px;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.id
     *
     * @return the value of source.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.id
     *
     * @param id the value for source.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.mc
     *
     * @return the value of source.mc
     *
     * @mbggenerated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.mc
     *
     * @param mc the value for source.mc
     *
     * @mbggenerated
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.px
     *
     * @return the value of source.px
     *
     * @mbggenerated
     */
    public Integer getPx() {
        return px;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.px
     *
     * @param px the value for source.px
     *
     * @mbggenerated
     */
    public void setPx(Integer px) {
        this.px = px;
    }
}